# Generated by Django 5.0.6 on 2024-07-05 03:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_chatroom_message_room"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="recipient",
        ),
    ]
