# Generated by Django 5.0.6 on 2024-07-05 06:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_remove_message_recipient"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="read",
            field=models.BooleanField(default=False),
        ),
    ]
